### ISSUE TITLE
correct search base?

### ISSUE THREAD

**Issue by theoneandonly-vector** [a-schild/inno-thinyldap#12]
what is the correct search-base?, is it always dc=aarboard dc=ch? or is it the hostname + domain or something else?

**Comment by theoneandonly-vector** [comment]
and is it compatible with reverse-proxy?

**Comment by a-schild** [comment]
As search base you can put in anything you wish, just make sure to use the same value on the phones/pbx's
Yes, it's compatible with the reverse proxy, for the RP the login must match this

LDAP

For LDAP the LDAP_BIND message is analysed. A user in the form <domain>\<user> is expected and the <domain> is matched to the Name of the configured host.

**Comment by theoneandonly-vector** [comment]
I can't connect to it through the reverse-proxy.
there are no firewall filters.
and when I connect using Softerra LDAP Broswer it tells me it can't load "RootDSE"

this is the inno-ldap error-log:
2018/08/31-13:23:03 Listener (type Net::Server::Fork) starting! pid(2420)
Resolved [*]:636 to [::]:636, IPv6
Not including resolved host [0.0.0.0] IPv4 because it will be handled by [::] IPv6
Resolved [*]:389 to [::]:389, IPv6
Not including resolved host [0.0.0.0] IPv4 because it will be handled by [::] IPv6
Binding to SSL port 636 on host :: with IPv6
Binding to TCP port 389 on host :: with IPv6
Group Not Defined.  Defaulting to EGID '0'
User Not Defined.  Defaulting to EUID '0'
2018/08/31-13:29:56 CONNECT SSL Peer: "[::ffff:192.0.0.8]:1704" Local: "[::ffff:192.168.0.250]:636"
Fri Aug 31 13:29:56 2018 Connection accepted from ::ffff:192.0.0.8 : 1704
2018/08/31-13:30:11 CONNECT SSL Peer: "[::ffff:192.0.0.8]:1706" Local: "[::ffff:192.168.0.250]:636"
Fri Aug 31 13:30:11 2018 Connection accepted from ::ffff:192.0.0.8 : 1706
2018/08/31-13:31:03 CONNECT SSL Peer: "[::ffff:192.0.0.8]:1707" Local: "[::ffff:192.168.0.250]:636"
Fri Aug 31 13:31:03 2018 Connection accepted from ::ffff:192.0.0.8 : 1707
2018/08/31-13:32:41 CONNECT SSL Peer: "[::ffff:192.0.0.8]:1709" Local: "[::ffff:192.168.0.250]:636"
Fri Aug 31 13:32:41 2018 Connection accepted from ::ffff:192.0.0.8 : 1709
2018/08/31-13:32:57 CONNECT SSL Peer: "[::ffff:192.0.0.8]:1711" Local: "[::ffff:192.168.0.250]:636"
Fri Aug 31 13:32:57 2018 Connection accepted from ::ffff:192.0.0.8 : 1711
2018/08/31-13:38:35 CONNECT SSL Peer: "[::ffff:192.0.0.8]:1730" Local: "[::ffff:192.168.0.250]:636"
Fri Aug 31 13:38:35 2018 Connection accepted from ::ffff:192.0.0.8 : 1730
2018/08/31-13:38:52 CONNECT SSL Peer: "[::ffff:192.0.0.8]:1731" Local: "[::ffff:192.168.0.250]:636"
Fri Aug 31 13:38:52 2018 Connection accepted from ::ffff:192.0.0.8 : 1731
2018/08/31-13:39:07 CONNECT SSL Peer: "[::ffff:192.0.0.8]:1732" Local: "[::ffff:192.168.0.250]:636"
Fri Aug 31 13:39:07 2018 Connection accepted from ::ffff:192.0.0.8 : 1732
2018/08/31-13:39:08 CONNECT SSL Peer: "[::ffff:192.0.0.8]:1733" Local: "[::ffff:192.168.0.250]:636"
Fri Aug 31 13:39:08 2018 Connection accepted from ::ffff:192.0.0.8 : 1733
Fri Aug 31 13:39:12 2018 No entries found: $VAR1 = {
          'or' => [],
          'present' => 'ObjectClass',
          'and' => []
        };

**Comment by theoneandonly-vector** [comment]
![image](https://user-images.githubusercontent.com/10380051/44910549-e7d8b600-ad23-11e8-8fcc-9a031edf22ea.png)

**Comment by a-schild** [comment]
You need to use a domain\user setting as mentioned in the reverse proxy documentation.
The domain part is then used to route your ldap query to the correct backend ldap server.

And you can't use ldap browser agains the thinyldap, the server missied all the advanced functions (Like schema/rootdse etc.) to allow interactive browsing

**Comment by theoneandonly-vector** [comment]
thx, but now I have another issue:
Fri Aug 31 14:52:24 2018 Lookup name A for meta.test.net\ldapuser in context dc=test,dc=net, maxAnswers <40>
DBD::mysql::st execute failed: Unknown column 'speeddial_phone' in 'field list' at /var/local/aarldap/InnoLdapServer.pm line 858.

**Comment by theoneandonly-vector** [comment]
and also this: 
se of uninitialized value in string eq at /var/local/aarldap/InnoLdapServer.pm
	line 203 (#1)
    (W uninitialized) An undefined value was used as if it were already
    defined.  It was interpreted as a "" or a 0, but maybe it was a mistake.
    To suppress this warning assign a defined value to your variables.

**Comment by theoneandonly-vector** [comment]
I now just deleted the speeddial lines. 2nd error still occure but I get my results :)

**Comment by theoneandonly-vector** [comment]
and how can I disbale tel-search? and logs so it doesnt use unnecessary ressources?

**Comment by theoneandonly-vector** [comment]
also umlauts aren't working for me

**Comment by a-schild** [comment]
You can disabled tel search somewhere on top of the InnoLdapServer.pm file

# ---- START CONFIGURATION SECTION ----
my $useTelSearch= 1; # Set to 0 if you not wish to use tel search

Umlauts should be working for everything, except searching with umlauts in ldap.
There exists a umlaut problem in the perl mysql driver.
I will look into the umlaut problem next week, how we can work arround the problem

Have you taken the sql script from the latest release? (I think I had fixed the missing column problem...)

**Comment by theoneandonly-vector** [comment]
yes it's from the latest release.

**Comment by theoneandonly-vector** [comment]
any update on disabling speeddial function/error ?

**Comment by theoneandonly-vector** [comment]
the problem with speeddial was an error of myself importing the data directly.. so I importet the fields "KW_Home" etc. directly into mysql.. which was expecting to have speeddial_home..

**Comment by a-schild** [comment]
So it's solved? Then please close the issue.

I have double checked it, and in the sql creation file, the field is created.

https://github.com/a-schild/inno-thinyldap/blob/master/ldap-server/db/phonebook.sql

**Comment by theoneandonly-vector** [comment]
yes, thx!
