### ISSUE TITLE
missing function ldap_connect when using reporting only on a LAP

### ISSUE THREAD

**Issue by bobobo-git** [a-schild/inno-thinyldap#20]
Thanks for enhancement in first place.

stumbled upon this problem when creating a reporting over an installed innophonebook as advised.
when setting the ldap-data in the reporting config it shows the php error message .. call to undefined ldap_connect, and stops working. it happened on a fresh install of a LAP on VMware and IPxx with no innovaphone application installed.  

I cured it with an

apt-get install php5-ldap

on the commandline

maybe an enhancement of the install.txt like this come handy

-- snip -- 

- Install php5 mysql libraries
  apt-get install php5-mysql  php-http
  apt-get install php5-ldap

-- snap--

**Comment by a-schild** [comment]
Thanks for this.
Is fixed in the docu.
