### ISSUE TITLE
Telefonbuch

### ISSUE THREAD

**Issue by j-roeber** [a-schild/inno-thinyldap#5]
Hallo Andrè,

können folgende Felder in die DB mit aufgenommen werden:

Fax
Adresse (Straße)
Stadt
PLZ

Fax finde ich wichtig, die anderen optional.
Mal so ein Gedanke: Wäre es nicht für die Suche besser die Person in Vorname Nachname zu unterteilen?
So könnte man im Telefonbuch nach Vor- oder Nachname suchen.

Mit freundlichen Grüßen

Jens Röber

**Comment by a-schild** [comment]
Soeben eine neue Version mit vielen neuen Feldern hinzugefügt.

- First name
- Last name
- Address
- Zip
- City
- Country
- Home
- KW Home

Migrationsalietung beachten!

**Comment by j-roeber** [comment]
Hallo Andrè,

 

bin leider erst jetzt dazu gekommen die neue Version bei mir zu testen. Läuft soweit ganz gut, nur mit der ldap Auflösung bei der Innovaphone klappt das nicht. Die Anlage fragt über das Reporting den LDAP-Server, aber es gibt keine Auflösung. Ich habe Dir mal das Logfile angehängt, da werden zwei Zeilen als fehlerhaft markiert. Die ldap Abfrage habe ich wie in der Update Anleitung konfiguriert. Die searchbase hatte ich einmal wie in deinem Screenshot eingetragen, ebenso habe ich es mit dc=company,dc=ch getestet. So wie mir das im Logfile aussieht bricht die Suche vorher ab.  

 

Mit freundlichen Grüßen

 

Jens Röber

 

 

     

 

Tel: +49 40 1802438-15

Fax: +49 40 1802438-99

Mobil: +49172 4222686

E-Mail: jens.roeber@it4u-sys.de <mailto:jens.roeber@it4u-sys.de> 

Web: www.it4u-systemhaus.de <http://www.it4u-sys.de/> 

 

Firmensitz: IT4U-Systemhaus GmbH, Saseler Mühlenweg 14, 22395 Hamburg

Geschäftführer: Thomas Doms, Jens Röber

Handelsregister: HRB 134664 Amtgericht Hamburg

 

Wichtiger Hinweis: Diese E-Mail könnte vertrauliche und/oder rechtlich geschützte Informationen enthalten. Sollten Sie nicht der richtige Adressat sein oder diese E-Mail irrtümlich erhalten haben, informieren Sie bitte sofort den Absender und vernichten Sie diese Mail sowie eventuelle Kopien davon dauerhaft von Ihrem System. Das unerlaubte Kopieren sowie die unbefugte Weitergabe dieser E-Mail sind unzulässig.

Important information: This email could contain confidential and/or legally protected information. If you are not the correct addressee or kept this E-Mail erroneous, please inform the sender immediately and destroy this mail as well as possible copies of it durably from your system. Bad copying as well as the unauthorized passing on of these email are not permitted.

 

Von: André Schild <notifications@github.com> 
Gesendet: Dienstag, 20. März 2018 23:40
An: a-schild/inno-thinyldap <inno-thinyldap@noreply.github.com>
Cc: j-roeber <jens.roeber@it4u-sys.de>; Author <author@noreply.github.com>
Betreff: Re: [a-schild/inno-thinyldap] Telefonbuch (#5)

 

Soeben eine neue Version mit vielen neuen Feldern hinzugefügt.

*	First name
*	Last name
*	Address
*	Zip
*	City
*	Country
*	Home
*	KW Home

Migrationsalietung beachten!

**Comment by a-schild** [comment]
In reporting auch die gleichen Felder hinterlegen wie hier dann müsste das eigentlich auch klappen..

https://github.com/a-schild/inno-thinyldap/wiki/Innovaphone-PBX-config

Du hast es ans Ticket auf Github gesendet, da kommen keine Anhänge an....
